#
# Automatically generated make config: don't edit
#

#
# Library Configuration
#

#
# Force build (Normally built when required)
#
CONFIG_LIB_LIBPTHREAD_FORCE=y
# CONFIG_LIB_LIBNVRAM_FORCE is not set
# CONFIG_LIB_LIBNTFS3G_FORCE is not set
# CONFIG_LIB_LIBBT_FORCE is not set
# CONFIG_LIB_READLINE_FORCE is not set
# CONFIG_LIB_LIBPCAP_FORCE is not set
# CONFIG_LIB_NCURSE_FORCE is not set
# CONFIG_LIB_FLEX_FORCE is not set
CONFIG_LIB_LIBUPNP_FORCE=y
# CONFIG_LIB_LIBDLNA_FORCE is not set
# CONFIG_LIB_LIBFFMPEG_FORCE is not set
# CONFIG_LIB_LIBGDBM_FORCE is not set
# CONFIG_LIB_LIBID3TAG_FORCE is not set
# CONFIG_LIB_PCRE_FORCE is not set
# CONFIG_LIB_ZLIB_FORCE is not set
CONFIG_LIB_LIBSTDC_PLUS_FORCE=y
# CONFIG_USER_HELLO_WORLD is not set

#
# Force build extra libraries in uClibc
#
CONFIG_LIB_CRYPT_FORCE=y
CONFIG_LIB_LIBM_FORCE=y
# CONFIG_LIB_NSL_FORCE is not set
CONFIG_LIB_UTIL_FORCE=y
CONFIG_LIB_RESOLV_FORCE=y
# CONFIG_LIB_RT_FORCE is not set
CONFIG_LIB_USB0112_FORCE=y
# CONFIG_LIB_USB100_FORCE is not set
CONFIG_LIB_LIBSTDC_PLUS_FORCE=y

#
# MTD utils
#
# CONFIG_USER_MTDUTILS is not set
# CONFIG_USER_MTDUTILS_ERASE is not set
# CONFIG_USER_MTDUTILS_ERASEALL is not set
# CONFIG_USER_MTDUTILS_FTL_CHECK is not set
# CONFIG_USER_MTDUTILS_FTL_FORMAT is not set
# CONFIG_USER_MTDUTILS_MKFSJFFS is not set
# CONFIG_USER_MTDUTILS_MKFSJFFS2 is not set
# CONFIG_USER_MTDUTILS_NFTLDUMP is not set
# CONFIG_USER_MTDUTILS_NFTL_FORMAT is not set
# CONFIG_USER_MTDUTILS_NANDDUMP is not set
# CONFIG_USER_MTDUTILS_NANDTEST is not set
# CONFIG_USER_MTDUTILS_NANDWRITE is not set
# CONFIG_USER_MTDUTILS_DOC_LOADBIOS is not set
# CONFIG_USER_MTDUTILS_DOC_LOADIPL is not set

#
# Network Applications
#
# CONFIG_USER_3G is not set
CONFIG_USER_BRCTL_BRCTL=y
# CONFIG_USER_BIGPOND is not set
# CONFIG_USER_BT_UTILS is not set
# CONFIG_USER_BT_AVINFO is not set
# CONFIG_USER_BT_BCCMD is not set
# CONFIG_USER_BT_CIPTOOL is not set
# CONFIG_USER_BT_HCICONFIG is not set
# CONFIG_USER_BT_HCIATTACH is not set
# CONFIG_USER_BT_HCISECFILTER is not set
# CONFIG_USER_BT_HCITOOL is not set
# CONFIG_USER_BT_L2PING is not set
# CONFIG_USER_BT_PPPORC is not set
# CONFIG_USER_BT_SDPTOOL is not set
# CONFIG_USER_CTORRENT is not set
# CONFIG_USER_DHCP6 is not set
# CONFIG_USER_DHCP6_SERVER is not set
# CONFIG_USER_DHCP6_CLIENT is not set
# CONFIG_USER_DNSMASQ is not set
# CONFIG_USER_DISKTYPE is not set
# CONFIG_USER_ECHO_SERVER is not set
# CONFIG_USER_STORAGE is not set
# CONFIG_USER_PROFTPD is not set
# CONFIG_USER_SAMBA is not set
# CONFIG_USER_GOAHEAD_HOSTNAME is not set
# CONFIG_USER_MTDAAPD is not set
# CONFIG_LIB_LIBGDBM_FORCE is not set
# CONFIG_LIB_LIBID3TAG_FORCE is not set
# CONFIG_USER_DNS_RESPONDER is not set
# CONFIG_USER_GOAHEAD_HTTPD is not set
# CONFIG_USER_GOAHEAD_IPV6 is not set
# CONFIG_USER_GOAHEAD_SSL is not set
# CONFIG_USER_GOAHEAD_HOSTNAME is not set
# CONFIG_USER_GOAHEAD_GreenAP is not set
# CONFIG_USER_WIZARD is not set
# CONFIG_USER_GOAHEAD_LANG_EN is not set
# CONFIG_USER_GOAHEAD_LANG_ZHTW is not set
# CONFIG_USER_GOAHEAD_LANG_ZHCN is not set
CONFIG_USER_GOAHEAD_LANG_EN=y
# CONFIG_USER_RALINKIAPPD is not set
CONFIG_USER_IGMP_PROXY=y
# CONFIG_USER_INADYN is not set
CONFIG_USER_IPTABLES_IPTABLES=y
# CONFIG_USER_IPTABLES_IP6TABLES is not set
# CONFIG_USER_IPSEC_TOOLS is not set
CONFIG_USER_IPROUTE2=y
# CONFIG_USER_IPROUTE2_SS is not set
# CONFIG_USER_IPROUTE2_NSTAT is not set
# CONFIG_USER_IPROUTE2_IFSTAT is not set
# CONFIG_USER_IPROUTE2_RTACCT is not set
# CONFIG_USER_IPROUTE2_LNSTAT is not set
# CONFIG_USER_IPROUTE2_IP is not set
# CONFIG_USER_IPROUTE2_RTMON is not set
CONFIG_USER_IPROUTE2_TC=y
CONFIG_LIB_LIBM_FORCE=y
# CONFIG_USER_MATRIXSSL is not set
# CONFIG_USER_MINIUPNPD is not set
# CONFIG_USER_MKDOSFS is not set
# CONFIG_USER_NTPCLIENT_NTPCLIENT is not set
# CONFIG_USER_NTPCLIENT_ADJTIMEX is not set
# CONFIG_USER_OPENSSL is not set
# CONFIG_USER_OPENSWAN is not set
# CONFIG_USER_P910ND is not set
# CONFIG_USER_PORTMAP is not set
# CONFIG_USER_PPPD is not set
# CONFIG_USER_PPPD_WITH_PPPOE is not set
# CONFIG_USER_PPPD_PPPSTATS is not set
# CONFIG_USER_PPPD_PPPDUMP is not set
# CONFIG_USER_PPPD_PPPCHAT is not set
# CONFIG_USER_RPPPPOE_RELAY is not set
# CONFIG_USER_RPPPPOE_SNIFF is not set
# CONFIG_USER_PPPOECD is not set
CONFIG_USER_PPTP_CLIENT=y
# CONFIG_USER_ZEBRA is not set
# CONFIG_LIB_LIBZEBRA_FORCE is not set
CONFIG_USER_RP_L2TP=y
# CONFIG_USER_RADVD is not set
# CONFIG_USER_RADVD_DUMP is not set
CONFIG_USER_802_1X=y
# CONFIG_USER_RT2561_802_1X is not set
# CONFIG_USER_SNORT is not set
# CONFIG_USER_SNMPD is not set
# CONFIG_USER_TOTD is not set
# CONFIG_USER_UVC_STREAM is not set
CONFIG_USER_UPNP_IGD=y
# CONFIG_USER_WPA_SUPPLICANT is not set
CONFIG_USER_WSC=y
CONFIG_LIB_LIBPTHREAD_FORCE=y
CONFIG_LIB_LIBUPNP_FORCE=y

#
# Wireless-tools
#
CONFIG_USER_WIRELESS_TOOLS=y
CONFIG_USER_WIRELESS_TOOLS_IWCONFIG=y
# CONFIG_USER_WIRELESS_TOOLS_IWGETID is not set
# CONFIG_USER_WIRELESS_TOOLS_IWLIST is not set
CONFIG_USER_WIRELESS_TOOLS_IWPRIV=y
# CONFIG_USER_WIRELESS_TOOLS_IWSPY is not set
# CONFIG_USER_WIRELESS_TOOLS_IWEVENT is not set

#
# Miscellaneous Applications
#
CONFIG_USER_BUSYBOX_BUSYBOX=y
# CONFIG_USER_BONNIE is not set
# CONFIG_USER_ETHTOOL is not set
# CONFIG_DHRYSTONE is not set
# CONFIG_DHCPFWD is not set
# CONFIG_USER_GDB_GDBREPLAY is not set
# CONFIG_USER_GDB_GDBSERVER is not set
# CONFIG_USER_IXIA_ENDPOINT is not set
# CONFIG_USER_LMBENCH3 is not set
CONFIG_USER_MTD_WRITE=y
# CONFIG_USER_MPSTAT is not set
# CONFIG_USER_NETCAT is not set
# CONFIG_USER_NETSTAT_NAT is not set
# CONFIG_USER_NTFS3G is not set
# CONFIG_USER_NTFSPROGS is not set
# CONFIG_LIB_LIBNTFS3G_FORCE is not set
# CONFIG_USER_STRACE_STRACE is not set
# CONFIG_USER_TCPDUMP is not set
# CONFIG_USER_PCIUTIL_LSPCI is not set
# CONFIG_USER_PCIUTIL_SETPCI is not set
# CONFIG_USER_LSUSB is not set
CONFIG_USER_USBMODESWITCH=y
CONFIG_LIB_USB0112_FORCE=y
CONFIG_USER_COMGT=y
CONFIG_USER_SDPARM=y
# CONFIG_USER_WATCHDOG is not set

#
# Ralink Proprietary Application
#
CONFIG_RALINKAPP=y
CONFIG_RALINKAPP_ATED=y
CONFIG_RALINKAPP_REG_RW=y
# CONFIG_RALINKAPP_CSR is not set
CONFIG_RALINKAPP_FLASH=y
CONFIG_RALINKAPP_HWNAT=y
# CONFIG_RALINKAPP_MII_MGR is not set
# CONFIG_RALINKAPP_NVRAM is not set
# CONFIG_RALINKAPP_L2_MANAGE is not set
CONFIG_RALINKAPP_GPIO=y
# CONFIG_RALINKAPP_SPI is not set
# CONFIG_RALINKAPP_I2C is not set
# CONFIG_RALINKAPP_MEMORY_USAGE is not set
# CONFIG_RALINKAPP_SWQOS is not set
# CONFIG_RALINKAPP_I2S is not set
# CONFIG_RALINKAPP_PCM is not set
# CONFIG_RALINKAPP_CLS is not set
# CONFIG_RALINKAPP_WAPI is not set
CONFIG_RALINKAPP_SCRIPTS=y

#
# Windows Rally Program
#
CONFIG_USER_LLTD=y

#
# ASUS Applications
#
CONFIG_ASUS_SHARED=y
CONFIG_ASUS_NVRAM_UTIL=y
CONFIG_ASUS_LIBDISK=y
CONFIG_ASUS_NETCONF=y
CONFIG_ASUS_RC=y
CONFIG_DPROXY=y
CONFIG_ASUS_INFOSVR=y
CONFIG_ASUS_DETECTWAN=y
CONFIG_ASUS_HTTPD=y
CONFIG_ASUS_WWW=y
CONFIG_PPPD=y
CONFIG_PPPOE_RELAY=y
CONFIG_BPALOGIN=y
CONFIG_TC=y
CONFIG_UDHCPD=y
CONFIG_ASUS_NTPCLIENT=y
CONFIG_EZ_IPUPDATE=y
CONFIG_VSFTPD=y
CONFIG_ASUS_SAMBA=y
CONFIG_ASUS_LPRNG=y
CONFIG_ASUS_U2EC=y
CONFIG_ASUS_WANDUCK=y
CONFIG_ASUS_NETWORK_MAP=y
CONFIG_ASUS_NTFS3G=y
CONFIG_USB_TEST=y
