
include $(TOPDIR)/config.mk

EXTRA_CFLAGS += -DMDC_MDIO_OPERATION -D_LITTLE_ENDIAN -I.
LIB	:= $(obj)librtk_switch.o

CFLAGS += $(EXTRA_CFLAGS)
CPPFLAGS += $(EXTRA_CFLAGS)

OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/acl.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/cpu.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/dot1x.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/eee.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/igmp.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/interrupt.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/l2.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/leaky.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/led.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/mirror.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/oam.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/port.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/ptp.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/qos.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rate.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rldp.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtk_switch.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_acl.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_cputag.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_dot1x.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_eav.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_eee.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_fc.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_green.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_hsb.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_igmp.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_inbwctrl.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_interrupt.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_led.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_lut.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_meter.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_mib.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_mirror.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_misc.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_oam.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_phy.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_port.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_portIsolation.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_qos.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_rldp.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_rma.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_scheduling.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_storm.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_svlan.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_trunking.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_unknownMulticast.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8367c_asicdrv_vlan.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/rtl8370mb.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/smi.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/stat.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/storm.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/svlan.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/trap.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/trunk.obj
OBJS-$(CONFIG_SWITCH_RTL8370MB_PHY_QCA8033_X2) += .objs/vlan.obj

COBJS	:= $(COBJS-y)
SRCS 	:= $(COBJS:.o=.c)
OBJS 	:= $(addprefix $(obj),$(COBJS))
OBJS	+= $(OBJS-y)

all:	$(LIB)

$(LIB):	$(obj).depend $(OBJS)
	$(call cmd_link_o_target, $(OBJS))


#########################################################################

# defines $(obj).depend target
include $(SRCTREE)/rules.mk

sinclude $(obj).depend

#########################################################################
